WebAcademy/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^syllabus/', include('syllabus.urls', namespace='syllabus')),
    url(r'^wizard/', include('wizard.urls', namespace='wizard')),
    url(r'^manage/', include('user.urls', namespace='user')),
    url(r'^export/', include('export.urls', namespace='export')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace='main')),
]

export/urls.py
from django.conf.urls import url

from export import views

urlpatterns = [
    url(r'^courses/$', views.CourseListView.as_view(), name='course-list'),
    url(r'^courses/(?P<pk>[0-9]+)/script$', views.CourseScriptView.as_view(), name='course-script'),

    url(r'^courses/(?P<pk>[0-9]+)$', views.CourseDetailView.as_view(), name='module-list'),
    url(r'^modules/(?P<pk>[0-9]+)/script$', views.ModuleScriptView.as_view(), name='module-script'),

    url(r'^modules/(?P<pk>[0-9]+)$', views.ModuleDetailView.as_view(), name='lesson-list'),
    url(r'^lessons/(?P<pk>[0-9]+)/script$', views.LessonScriptView.as_view(), name='lesson-script'),

    url(r'^lessons/(?P<pk>[0-9]+)$', views.LessonDetailView.as_view(), name='unit-list'),
    url(r'^units/(?P<pk>[0-9]+)/script$', views.UnitScriptView.as_view(), name='unit-script'),
]

main/urls.py
from django.conf.urls import url

from main import views

urlpatterns = [
    url(r'^$', views.index, name='home'),
]

# ToDo add error views

export/models.py
# Create your models here.

main/models.py
# Create your models here.

export/views.py
# Create your views here.
from django.views.generic import ListView, DetailView

from syllabus.models import Course, Module, Lesson, Unit
from user.views import LoginRequiredMixin


class CourseListView(LoginRequiredMixin, ListView):
    model = Course
    context_object_name = 'courses'
    template_name = 'export/course-list.html'


class CourseScriptView(LoginRequiredMixin, DetailView):
    model = Course
    context_object_name = 'course'
    content_type = 'text/plain'
    template_name = 'export/scripts/base-script'


class CourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    context_object_name = 'course'
    template_name = 'export/module-list.html'


class ModuleScriptView(LoginRequiredMixin, DetailView):
    model = Module
    context_object_name = 'module'
    content_type = 'text/plain'
    template_name = 'export/scripts/base-script'


class ModuleDetailView(LoginRequiredMixin, DetailView):
    model = Module
    context_object_name = 'module'
    template_name = 'export/lesson-list.html'


class LessonScriptView(LoginRequiredMixin, DetailView):
    model = Lesson
    context_object_name = 'lesson'
    content_type = 'text/plain'
    template_name = 'export/scripts/base-script'


class LessonDetailView(LoginRequiredMixin, DetailView):
    model = Lesson
    context_object_name = 'lesson'
    template_name = 'export/unit-list.html'


class UnitScriptView(LoginRequiredMixin, DetailView):
    model = Unit
    context_object_name = 'unit'
    content_type = 'text/plain'
    template_name = 'export/scripts/base-script'

main/views.py
from django.shortcuts import redirect


# Create your views here.

def index(request):
    if request.user is not None:
        if request.user.is_active:
            return redirect('user:dashboard')
        else:
            return redirect('user:not-active')
    else:
        return redirect('user:login-form')

export/templates/export/course-list.html
{% extends "export/main.html" %}

{% block content %}
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">Courses:</h2>
    </div>
    {% include 'export/table/table.html' %}
{% endblock %}

export/templates/export/lesson-list.html
{% extends "export/main.html" %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li><a href="{% url 'export:module-list' module.course.id %}">{{ module.course.title }}</a></li>
        <li class="active">{{ module.title }}</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">Lessons:</h2>
    </div>
    {% include 'export/table/table.html' %}
{% endblock %}

export/templates/export/main.html
{% extends "layout.html" %}

{% block main %}
    {% block breadcrumbs %}
    {% endblock %}
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--2-col"></div>
        <div class="mdl-cell mdl-cell--8-col">
            {% block content %}
            {% endblock %}
        </div>
        <div class="mdl-cell mdl-cell--2-col"></div>
    </div>
{% endblock %}

export/templates/export/module-list.html
{% extends "export/main.html" %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="active">{{ course.title }}</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">Modules:</h2>
    </div>
    {% include 'export/table/table.html' %}
{% endblock %}

export/templates/export/unit-list.html
{% extends "export/main.html" %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li><a href="{% url 'export:module-list' lesson.module.course.id %}">{{ lesson.module.course.title }}</a>
        </li>
        <li><a href="{% url 'export:lesson-list' lesson.module.id %}">{{ lesson.module.title }}</a></li>
        <li class="active">{{ lesson.title }}</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">Units:</h2>
    </div>
    {% include 'export/table/table.html' %}
{% endblock %}